name: dls_squad_brain
description: DLS Squad Brain V2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.4.4
  material_color_utilities: ^0.13.4

flutter:
  uses-material-design: true
